### ISSUE TITLE
Choose a U.I design

### ISSUE THREAD

**Issue by HHHMHA** [TheKiddos/expensia#12]
You can choose any design you like but may I recommend these two:
https://dribbble.com/shots/14902012-Dashboard-UI-Exploration
https://dribbble.com/shots/10604883-Tracker

**Comment by Mouiad-JRA** [comment]
@HHHMHA FOR me I suggest this 
https://dribbble.com/shots/15654856-Fundbatch-Dashboard
or 
https://dribbble.com/shots/14902012-Dashboard-UI-Exploration
But it'll be better to have the first one (Of course after modifying it)

**Comment by HHHMHA** [comment]
We are going to implement this:
https://dribbble.com/shots/15654856-Fundbatch-Dashboard
