### ISSUE TITLE
Implement Expense API

### ISSUE THREAD

**Issue by HHHMHA** [TheKiddos/expensia#5]
Operations:
CRUD

Model:
`
name
amount
date
category
`

All fields are **REQUIRED**
Must be managed by admin.
Can be accessed by any one.

List endpoint must allow filtering using a start and end dates.

**Comment by HHHMHA** [comment]
@Mouiad-JRA Start you little piece of filth

**Comment by Mouiad-JRA** [comment]
Check and test it before merging you BITCH
